Improve shutdown logic and auto-exclude vital sessions from logout
Use the list of excluded iSCSI sessions generated by umountiscsi.sh to
selectively log out from targets at shutdown. But in contrast to
before, other sessions will be logged out now. Provide a new option to
revert to the old behavior of not logging out from any target (for
those cases where the storage stack isn't detected properly).

Separate logout logic into separate script that may later be called
from native systemd service.

diff --git a/debian/open-iscsi.init b/debian/open-iscsi.init
--- a/debian/open-iscsi.init
+++ b/debian/open-iscsi.init
@@ -152,34 +152,41 @@ stoptargets() {
 	sync
 	# only logout if daemon is running, iscsiadm hangs otherwise
         if [ -s $PIDFILE ] && kill -0 `sed -n 1p $PIDFILE` >/dev/null ; then
-		$ADM -m node --logoutall=all
+		/lib/open-iscsi/logout-all.sh
         fi
 
 	log_end_msg 0
 }
 
 stop() {
-	if [ -f /etc/iscsi/iscsi.initramfs ]; then
-		log_warning_msg "/etc/iscsi/iscsi.initramfs present, not stopping iscsid yet"
-		return 0
-	fi
-
-	# Call umountiscsi.sh to unmount iSCSI devices first
+	# Call umountiscsi.sh to unmount iSCSI devices first (always do
+	# that, regardless of whether root is on iSCSI, umountiscsi.sh
+	# will exclude it - and even if that shouldn't work, the mount
+	# point will be busy)
 	/lib/open-iscsi/umountiscsi.sh
-	exit_status=$?
-	if [ $exit_status -ne 0 ]; then
-		log_failure_msg "Couldn't unmount all iSCSI devices. Cannot stop iSCSI service"
+	umount_exit_status=$?
+
+	if [ $umount_exit_status -ne 0 ]; then
+		log_failure_msg "Couldn't unmount all iSCSI devices. not logging out from any target."
 		exit 1
 	fi
 
 	stoptargets
 
-	log_daemon_msg "Stopping iSCSI initiator service"
-	start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal TERM --exec $DAEMON
-	rm -f $PIDFILE
-	modprobe -r ib_iser 2>/dev/null
-	modprobe -r iscsi_tcp 2>/dev/null
-	log_end_msg 0
+	# Don't stop iscsid if we're on initramfs or we had some
+	# excluded sessions. We could actually stop it, it's not
+	# required for the kernel to continue working with active
+	# sessions, but it doesn't hurt to leave it running.
+	# (Note that on systemd systems, it will be killed
+	# regardless.)
+	if [ ! -f /etc/iscsi/iscsi.initramfs ] && 
+		( [ ! -f /run/open-iscsi/shutdown-keep-sessions ] || [ -z "$(cat /run/open-iscsi/shutdown-keep-sessions)" ] )
+	then
+		log_daemon_msg "Stopping iSCSI initiator service"
+		start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal TERM --exec $DAEMON
+		rm -f $PIDFILE
+		log_end_msg 0
+	fi
 }
 
 restart() {
