don't stop iscsi if an iscsi device fails to umount

diff --git a/debian/open-iscsi.init b/debian/open-iscsi.init
--- a/debian/open-iscsi.init
+++ b/debian/open-iscsi.init
@@ -132,6 +132,16 @@ stop() {
 		log_warning_msg "/etc/iscsi/iscsi.initramfs present, not stopping iscsid yet"
 		return 0
 	fi
+
+	# Call umountiscsi.sh to unmount iSCSI devices first
+	log_daemon_msg "Unmounting iSCSI devices"
+	/etc/init.d/umountiscsi.sh stop
+	exit_status=$?
+	if [ $exit_status -ne 0 ]; then
+		log_failure_msg "Couldn't unmount all iSCSI devices. Cannot stop iSCSI service"
+		exit 1
+	fi
+
 	stoptargets
 	log_daemon_msg "Stopping iSCSI initiator service"
 	start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal KILL --exec $DAEMON
diff --git a/debian/umountiscsi.sh.init b/debian/umountiscsi.sh.init
--- a/debian/umountiscsi.sh.init
+++ b/debian/umountiscsi.sh.init
@@ -15,22 +15,40 @@
 do_stop () {
     log_daemon_msg "Unmounting iscsi-backed filesystems"
 
+    umount_fail=0
+
     for HOST_DIR in /sys/devices/platform/host*; do
 	if ! [ -d $HOST_DIR/iscsi_host* ]; then
 	    continue
 	fi
-	for TARGET_DIR in $HOST_DIR/session*/target*/*\:*; do
-	    for BLOCK_FILE in $TARGET_DIR/block\:*; do
-		BLOCK_DEV=`echo "$BLOCK_FILE" | sed 's/.*block\://'`
-		DOS_PARTITIONS="`awk "/^\/dev\/$BLOCK_DEV/ { print \\$2; }" < /proc/mounts`"
-		for DEVICE in $DOS_PARTITIONS; do
-		    log_progress_msg $DEVICE
-		    umount $DEVICE
+        for SESSION_DIR in $HOST_DIR/session*; do
+		if ! [ -d $SESSION_DIR/target* ]; then
+			continue
+		fi
+		for BLOCK_FILE in $SESSION_DIR/target*/*\:*/block/*; do
+			BLOCK_DEV=`echo "$BLOCK_FILE" | sed 's/.*block\///'`
+			DOS_PARTITIONS="`awk "/^\/dev\/$BLOCK_DEV/ { print \\$2; }" < /proc/mounts`"
+			for DEVICE in $DOS_PARTITIONS; do
+				#log_progress_msg $DEVICE
+				#echo $DEVICE
+				umount $DEVICE
+				exit_status=$?
+				if ! [ $exit_status -eq 0 ]; then
+					umount_fail=`expr $umount_fail + 1`
+					log_warning_msg "Could not unmount $DEVICE"
+				fi
+			done
 		done
-	    done
 	done
     done
-    log_end_msg 0
+
+    if [ $umount_fail -ne 0 ]; then
+	    log_end_msg 1
+	    exit 1
+    else
+	    log_end_msg 0
+	    exit 0
+    fi
 }
 
 case "$1" in
